#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Check Prettier standards
yarn check-types ||
{
    echo 'Failed Type check.
        Change the type errors and rerun'
    false;
}

yarn check-format ||
(
    echo 'Prettier Check Failed.
        Run yarn format, add changes and try commit again.';
    false;
)

yarn test ||
(
    echo 'Unit tests failed
        Run yarn test before your commit to verify everything is working'
    false;
)

echo '✅ Nice work! Committing now. ✅'
